-- Use a high-level role to create the environment
USE ROLE ACCOUNTADMIN;

-- 1. Create a dedicated Role and User
CREATE ROLE IF NOT EXISTS AIRBYTE_ROLE;
CREATE USER IF NOT EXISTS AIRBYTE_USER 
    PASSWORD = '<AIRBYTE_SERVICE_ACCOUNT_PASSWORD>' 
    DEFAULT_ROLE = AIRBYTE_ROLE;
GRANT ROLE AIRBYTE_ROLE TO USER AIRBYTE_USER;

-- 2. Create a Warehouse (the "engine" that moves the data)
CREATE WAREHOUSE IF NOT EXISTS AIRBYTE_WAREHOUSE 
    WAREHOUSE_SIZE = 'XSMALL' 
    AUTO_SUSPEND = 60 
    AUTO_RESUME = TRUE;
GRANT USAGE ON WAREHOUSE AIRBYTE_WAREHOUSE TO ROLE AIRBYTE_ROLE;

-- 3. Create the Database and Schema
CREATE DATABASE IF NOT EXISTS AIRBYTE_DB;
GRANT OWNERSHIP ON DATABASE AIRBYTE_DB TO ROLE AIRBYTE_ROLE;

-- 4. Give Airbyte permission to create its own schemas inside this DB
GRANT CREATE SCHEMA ON DATABASE AIRBYTE_DB TO ROLE AIRBYTE_ROLE;

-- Give your current user access to see what Airbyte is doing
GRANT ROLE AIRBYTE_ROLE TO USER shawnwaller;